# Root Docker Compose - convenience wrapper for deployment configs
# 
# Usage:
#   Production: docker-compose up
#   Development: docker-compose -f docker-compose.dev.yml up
#   With monitoring: docker-compose --profile monitoring up

# This file extends the production configuration
include:
  - deployment/docker/docker-compose.yml